### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by bluebear94**

### CODE REVIEW

**Comment by NamedKitten** [comment]
We recomend having the user use a seporate dir for building. E.g: `build/`

**Comment by bluebear94** [comment]
Some people do prefer in-source builds.

**Comment by Aidoboy** [comment]
I'm fine with the additions to the gitignore, but the extra boost includes aren't needed and the added dump may actually cause problems.

**Comment by bluebear94** [comment]
The `#include <boost/asio.hpp>` are necessary for the files to compile.

**Comment by Aidoboy** [comment]
What build system are you using? I'm compiling with clang on Ubuntu 17.04.

**Comment by bluebear94** [comment]
I'm using g++ (an experimental 8.0.0 build) on Ubuntu 17.04.

**Comment by Aidoboy** [comment]
What if you use a stable version of g++?

**Pull request closed without merging**
