### PR TITLE
Add more support for including discordpp in other CMake projects

### PR DESCRIPTION
**Pull request by JosiahWI**
This will export a target called discordpp::discordpp which projects can include with find_package, and will add an alias target by the same name so that adding it as a subdirectory has the same behavior. I had to bump the minimum version to 3.8 because CMake forbids setting the cxx standard properties on interface libraries, and the cxx_std_14 feature is first available in 3.8. Additionally I have added a version range to up to 3.18 which is the version I tested on. This doesn't restrict people from using newer versions, but it sets CMake policies for versions within the range.

### CODE REVIEW

**Comment by UndarkAido** [comment]
Hmm, that's interesting. I moved a little bit in this direction on the `dev-restructure` branch, I'd really prefer to keep sweeping CMake changes there for now.

Currently the plan was to merge `dev-restructure` for a 1.0 release once I'm happy with it with CPM support though this might be a good offering too. I'm not certain if installing a singular version of Discord++ on a system is the best idea but it's something to think about.

Are you on the Discord server?

**Comment by JosiahWI** [comment]
I should PR this to that branch then. Any way to change that without recreating the PR?

I'm not in the discord server, but I can join it.

**Comment by niansa** [comment]
This branch has conflicts that must be resolved <- does not seem to work @JosiahWI

**Comment by JosiahWI** [comment]
Could you elaborate on what doesn't work? Without steps to reproduce I can't tell what the issue is. When I tested this before initiating the PR, it worked as expected.

**Comment by JosiahWI** [comment]
I need to commit one more thing before this is mergeable. I need to export the nhlomann-json target and the discordpp target, both, for this to work properly.

**Comment by UndarkAido** [comment]
> Could you elaborate on what doesn't work? Without steps to reproduce I can't tell what the issue is. When I tested this before initiating the PR, it worked as expected.

I think he was talking about the merge conflict after you changed branches

**Comment by JosiahWI** [comment]
This is now tested with a nlohmann_json installation and configures correctly.

**Comment by JosiahWI** [comment]
Closing, because I reconsidered the scope of discordpp and I don't think this is helpful to the project for all the work required to do it for every plugin.

**Comment by UndarkAido** [comment]
Yeah, I'd like to put some work into making stuff work easily with FetchContent or similar. I think that's maybe more convenient.

**Pull request closed without merging**
