### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by arves100**
This commt add support for Microsoft Visual C++ Compiler
I tested this on VS2017

Libs i used:
cURL 7.54.1 (from official site)
Win32 OpenSSL 1.1+ (1.0+ dosen't export some deprecated functions to make boost::aiso works)
Websocket++ 0.8.0-dev (because version 0.7 dosen't have OpenSSL 1.1 support)
Boost 1.64 builded from source

### CODE REVIEW

**Comment by AraHaan** [comment]
smh, what if I dont want dpp to be an DLL on windows? What if I just want to link discordPP into my bot's main application?

**Comment by arves100** [comment]
I was forced to use OpenSSL over WinSSL because Discord++ uses WebSocket++ as networking library. WebSocket++ uses Boost Asio and i don't think it's compatble with WinSSL, also i think Boost Asio uses WinSock2 for networking purpouses.

It normally generate a VS Project, i don't know if CMake generate a NMake project, if you can't use Visual Studio you can still use msbuild.

I didn't do the static library stuff because i didn't see that discordpp could also be builded as a static library.

**Comment by arves100** [comment]
Anyway the library it's now header-only, this pull request it's pontless now

**Comment by AraHaan** [comment]
Yeah, not only that but actually asio (in Technical Specification form) uses ``winsock2.h``.

**Pull request closed without merging**
